version: 0.0
os: ubuntu
files:
  - source: /
    destination: /home/ubuntu/app/step2/zip/
    overwrite: yes

#permission:
#  - object: /home/ubuntu/
#    owner: bvoat
#    group: ubuntu
#
#hook:
#  deployment-lifecycle-event-name:
#    - location: script-location
#      timeout: timeout-in-seconds
#      runas: user-name