version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    -location: deploy.sh
#permission:
#  - object: /home/ubuntu/
#    owner: bvoat
#    group: ubuntu
#
#hook:
#  deployment-lifecycle-event-name:
#    - location: script-location
#      timeout: timeout-in-seconds
#      runas: user-name